import Fs from 'node:fs'
import Path from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO = Path.join(Path.dirname(fileURLToPath(import.meta.url)), '..')

// The reader-facing set. This repository is a dashboard generator, not a
// library: it has one README, and everything else here is a program. The
// style guide is deliberately out, as it is everywhere in the fleet: it
// quotes the patterns it bans. The page a reader actually sees is generated by
// site/render.mjs and is covered separately, by
// `published-pages-follow-the-punctuation-rulings` in docs.test.mjs.
const PAGES = [
  'README.md',
]

// No tutorial here, so "we" is allowed nowhere and the exclamation
// ration is zero.
const TUTORIALS = []

const exists = (rel) => Fs.existsSync(Path.join(REPO, rel))

export const gatedDocs = () => PAGES.filter(exists)
export const tutorials = () => TUTORIALS.filter(exists)

if (import.meta.url === `file://${process.argv[1]}`) {
  process.stdout.write(gatedDocs().join('\n') + '\n')
}
