import Fs from 'node:fs'
import Path from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO = Path.join(Path.dirname(fileURLToPath(import.meta.url)), '..')

// The reader-facing set. This repository is a dashboard generator, not a
// library: it has one README, and everything else here is a program. The
// style guide is deliberately out, as it is everywhere in the fleet: it
// quotes the patterns it bans. The page a reader actually sees is generated by
// site/render.mjs and is covered separately, by
// `published-pages-follow-the-punctuation-rulings` in docs.test.mjs.
const PAGES = [
  'README.md',
]

// No tutorial here, so "we" is allowed nowhere and the exclamation
// ration is zero.
const TUTORIALS = []

const exists = (rel) => Fs.existsSync(Path.join(REPO, rel))

// A declared page that is not on disk THROWS.
//
// This filtered instead, and the comment here claimed the filter made a
// renamed page "fail as a missing gate". It did the opposite: the page
// left the list, both halves of the gate carried on over what remained,
// and the coverage test passed because it only counts what the list
// returned. Deleting a page was the one way to stop it being checked.
const present = (declared, what) => {
  const gone = declared.filter((f) => !exists(f))
  if (0 < gone.length) {
    throw new Error(
      `gated-docs: declared ${what} but not on disk: ` + gone.join(', ') +
      '. Rename it here, or delete the entry deliberately.')
  }
  return declared
}

export const gatedDocs = () => present(PAGES, 'gated')
export const tutorials = () => present(TUTORIALS, 'a tutorial')

if (import.meta.url === `file://${process.argv[1]}`) {
  process.stdout.write(gatedDocs().join('\n') + '\n')
}
